In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
list_2D = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
tensor_2D = torch.tensor(list_2D)
print(tensor_2D)
print('Dimensions:', tensor_2D.ndimension())
print('Shape:', tensor_2D.shape)

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])
Dimensions: 2
Shape: torch.Size([3, 3])


In [8]:
arr_2D = tensor_2D.numpy()
new_tensor = torch.from_numpy(arr_2D)
print(arr_2D)
print(new_tensor)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])


In [11]:
df = pd.DataFrame({'a':[11,21,31],'b':[12,22,312]})
tensor_for_df = torch.tensor(df.values)
print(tensor_for_df)

tensor([[ 11,  12],
        [ 21,  22],
        [ 31, 312]])


In [15]:
df = pd.DataFrame({'A':[11, 33, 22],'B':[3, 3, 2]})
practice_tensor = torch.tensor(df.values)
print(practice_tensor)

tensor([[11,  3],
        [33,  3],
        [22,  2]])


In [22]:
tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(tensor_example.numpy())
print("What is the value on 1st-row first two columns?", tensor_example[0,0:2].numpy())
print("What is the value on 3rd-column last two rows?", tensor_example[-2:, 2].numpy())

[[11 12 13]
 [21 22 23]
 [31 32 33]]
What is the value on 1st-row first two columns? [11 12]
What is the value on 3rd-column last two rows? [23 33]


In [21]:
sliced_tensor = tensor_example[0:2, 1:3]
print(sliced_tensor)

tensor([[12, 13],
        [22, 23]])


In [23]:
tensor_ques = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
# Try to change the values on the second column and the last two rows to 0
tensor_ques[-2:, 1] = 0
print(tensor_ques.numpy())

[[11 12 13]
 [21  0 23]
 [31  0 33]]


In [25]:
x = torch.tensor([[1, 0],[0, 1]]) 
y = torch.tensor([[2, 1],[1, 2]])
z = x + y
print(z)
two_y = y * 2
print(y)

tensor([[3, 1],
        [1, 3]])
tensor([[2, 1],
        [1, 2]])


In [36]:
# Practice
x = torch.tensor([[1,3],[4,5],[2,7]])
y = torch.tensor([[2,1,5],[4,2,8]])
print(x.shape, ',',y.shape)
z = torch.mm(y, x)
print(z)

torch.Size([3, 2]) , torch.Size([2, 3])
tensor([[16, 46],
        [28, 78]])
