# 2nd Place Submission in AIS Winter 2021 Competition
## Author: James Yang

In [1]:
import numpy as np
import pandas as pd 
import os
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score


In [2]:
train = pd.read_csv('../Data/stars_train.csv')
test = pd.read_csv('../Data/stars_competitor_test.csv')

train = pd.get_dummies(data=train,columns=["Color","Spectral_Class"],drop_first=True)

y = train["Type"]
train = train.drop("Type", axis=1)


test = pd.get_dummies(data=test,columns=["Color","Spectral_Class"],drop_first=True)
test = test.drop("ID", axis=1)

train, test = train.align(test, join='left', axis=1, fill_value= 0)
scaler = StandardScaler()
scaler.fit(train)
train_scale = scaler.transform(train)
test_scale = scaler.transform(test)


In [3]:
train_scale

array([[-0.75340035, -0.60969708, -0.46178412, ..., -0.16903085,
         1.15003506, -0.46940279],
       [ 1.25577401,  0.05127642, -0.39311411, ..., -0.16903085,
        -0.86953871,  2.13036653],
       [-0.67073141,  2.66914785,  2.05336075, ...,  5.91607978,
        -0.86953871, -0.46940279],
       ...,
       [ 1.26555427,  1.20053759, -0.29747397, ..., -0.16903085,
        -0.86953871,  2.13036653],
       [-0.78006443, -0.60969707, -0.46174357, ..., -0.16903085,
         1.15003506, -0.46940279],
       [-0.83411324, -0.60969708, -0.46172635, ..., -0.16903085,
         1.15003506, -0.46940279]])

In [4]:
test_scale

array([[-0.7565918 , -0.60969708, -0.46182716, ..., -0.16903085,
         1.15003506, -0.46940279],
       [ 0.1334119 , -0.60611117, -0.44856627, ..., -0.16903085,
        -0.86953871, -0.46940279],
       [-0.83092178, -0.60969708, -0.46181128, ..., -0.16903085,
         1.15003506, -0.46940279],
       ...,
       [-0.78469718, -0.60969707, -0.46130553, ..., -0.16903085,
         1.15003506, -0.46940279],
       [-0.82608313, -0.60969707, -0.46176078, ..., -0.16903085,
         1.15003506, -0.46940279],
       [-0.81753827, -0.60969708, -0.46180305, ..., -0.16903085,
         1.15003506, -0.46940279]])

In [5]:
"""
KNN code, not used

parameters = [
    {'n_neighbors': list(np.arange(2,20+1))}
]
opt_knn = KNeighborsClassifier()

grid_search = GridSearchCV(opt_knn, parameters, scoring='accuracy', return_train_score=True)

grid_search.fit(train_scale, y)

predictions = grid_search.predict(train_scale)

accuracy = accuracy_score(y, predictions)

predictions, y, accuracy
#grid_search.best_params_
knncv = cross_val_score(grid_search, train_scale, y, cv=5)
knncv

prediction = grid_search.predict(test_scale)

print(prediction)
df= pd.DataFrame({'Predicted': prediction})
df.to_csv("Prediction.csv")
"""


'\nKNN code, not used\n\nparameters = [\n    {\'n_neighbors\': list(np.arange(2,20+1))}\n]\nopt_knn = KNeighborsClassifier()\n\ngrid_search = GridSearchCV(opt_knn, parameters, scoring=\'accuracy\', return_train_score=True)\n\ngrid_search.fit(train_scale, y)\n\npredictions = grid_search.predict(train_scale)\n\naccuracy = accuracy_score(y, predictions)\n\npredictions, y, accuracy\n#grid_search.best_params_\nknncv = cross_val_score(grid_search, train_scale, y, cv=5)\nknncv\n\nprediction = grid_search.predict(test_scale)\n\nprint(prediction)\ndf= pd.DataFrame({\'Predicted\': prediction})\ndf.to_csv("Prediction.csv")\n'

In [6]:
"""
Linear SVM Code, not used

from sklearn.svm import LinearSVC

clf = LinearSVC()
clf.fit(train_scale, y)

svmcv = cross_val_score(clf, train_scale, y, cv=5)
print(svmcv)

prediction = clf.predict(test_scale)

print(prediction)
df= pd.DataFrame({'Predicted': prediction})
df.to_csv("Prediction.csv")
"""

'\nLinear SVM Code, not used\n\nfrom sklearn.svm import LinearSVC\n\nclf = LinearSVC()\nclf.fit(train_scale, y)\n\nsvmcv = cross_val_score(clf, train_scale, y, cv=5)\nprint(svmcv)\n\nprediction = clf.predict(test_scale)\n\nprint(prediction)\ndf= pd.DataFrame({\'Predicted\': prediction})\ndf.to_csv("Prediction.csv")\n'

In [7]:
from sklearn.ensemble import RandomForestClassifier

parameters = [
    {'n_estimators': list(np.arange(10,20))}
]

clf = RandomForestClassifier()

grid_search = GridSearchCV(clf, parameters, scoring='accuracy', return_train_score=True)
grid_search.fit(train_scale, y)
predictions = grid_search.predict(train_scale)
accuracy = accuracy_score(y, predictions)

#predictions, y, accuracy
print(grid_search.best_params_)


rfccv = cross_val_score(grid_search, train_scale, y, cv=5)
print(rfccv)


{'n_estimators': 12}
[1.         1.         1.         0.96551724 0.96428571]




```

```



In [8]:
predictions = grid_search.predict(test_scale)
print(predictions)
df= pd.DataFrame({'Predicted': predictions})
df.to_csv("Prediction.csv")

[0 3 0 3 2 5 3 4 5 5 4 0 5 4 1 2 1 4 3 1 3 0 2 0 0 1 2 2 2 0 3 1 3 1 2 5 5
 5 0 5 4 3 4 1 2 1 0 5 1 2 3 4 0 0 1 0 1 2 5 4 0 1 3 2 5 1 5 0 2 0 5 3 0 4
 4 0 2 2 2 5 5 1 4 4 2 4 4 4 5 2 3 3 1 1 0 0]
