Decision Tree

In [38]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
%matplotlib inline

In [24]:
df = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/drug200.csv')

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [33]:
x_data = df[['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']].to_numpy()

In [34]:
from sklearn import preprocessing
label_sex = preprocessing.LabelEncoder()
label_sex.fit(['F', 'M'])
x_data[:,1] = label_sex.transform(x_data[:,1]) # all rows in column index 1 ('Sex')

label_BP = preprocessing.LabelEncoder()
label_BP.fit([ 'LOW', 'NORMAL', 'HIGH'])
x_data[:,2] = label_BP.transform(x_data[:,2])

label_Chol = preprocessing.LabelEncoder()
label_Chol.fit([ 'NORMAL', 'HIGH'])
x_data[:,3] = label_Chol.transform(x_data[:,3])

In [36]:
y_data = df['Drug']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3, random_state=3)
print('Training Data\'s shapes: ', x_train.shape, y_train.shape)
print('Testing Data\'s shapes: ', x_test.shape, y_test.shape)

Training Data's shapes:  (140, 5) (140,)
Testing Data's shapes:  (60, 5) (60,)


In [37]:
drugTree = DecisionTreeClassifier(criterion='entropy', max_depth=4)
drugTree.fit(x_train, y_train)
y_hat = drugTree.predict(x_test)

In [39]:
from sklearn import metrics
print('Confusion matrix: \n', metrics.confusion_matrix(y_test, y_hat))
print('Accuracy Score: %.3f' % metrics.accuracy_score(y_test, y_hat))

Confusion matrix: 
 [[ 7  0  0  0  0]
 [ 0  5  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 20  1]
 [ 0  0  0  0 22]]
Accuracy Score: 0.983
